### ISSUE TITLE
Scrape ACV data for classes from last cohort

### ISSUE THREAD

**Issue by 20jasper** [20jasper/100Devs-Statistics-Project#1]
- [ ] Get Average concurrent viewers data and the date of all streams from the last cohort of 100Devs
- [ ] Mark each stream as a class stream, an office hours stream, or other

**Comment by nfolkman** [comment]
I've been thinking about building a data scraper recently, need help with this issue?

**Comment by 20jasper** [comment]
I think @Snake0good is working on it already, so talk to him and see where he's at with it and see how you can help
