### ISSUE TITLE
Replace forms with a link to the issues page on github

### ISSUE THREAD

**Issue by 20jasper** [20jasper/100Devs-Statistics-Project#19]
- [ ] change the text that says "contact us" to something like "Found a bug or have a feature request? Make an issue on GitHub"
- [x] remove the form
- [x] Add an anchor tag with this link https://github.com/20jasper/100Devs-Statistics-Project/issues/

**Comment by floorrinse** [comment]
Is this on the index page?

**Comment by 20jasper** [comment]
It's on the index and contributors and all the graph pages, so every page as far as I know

**Comment by DekotaNelson** [comment]
VS code has a find and replace function that can replace peices of code in all files quickly, it's great for editing footers/headers/menus anything that is shared through multiple pages that need changed. Wanted to mention it in case y'all weren't aware of it. Should help make changing this easier

**Comment by floorrinse** [comment]
Volunteering this one 👍

**Comment by NeffCodes** [comment]
Note,  we could keep the form and just use Netlify forms to handle the submissions.

**Comment by 20jasper** [comment]
I felt like it would be better to have it go to the issues page since forms will go to one person's email instead of anyone who wants to fix an issue being able to work on it immediately
