### ISSUE TITLE
Website Design/Layout

### ISSUE THREAD

**Issue by curtisbarnard** [20jasper/100Devs-Statistics-Project#2]
Create a layout via a sketched wireframe or figma of how the website will be laid out.

**Comment by floorrinse** [comment]
Figure out if we should include a mobile responsive design

**Comment by 20jasper** [comment]
I feel like every site should mobile responsive. I paid for pixelarity, so if anyone finds a good template from there, just ask me and I can add it to the repo. https://pixelarity.com/

**Comment by DekotaNelson** [comment]
What about pixelarity's Phantom? Seems like it would be perfect for a site based off graphs/data. We could replace the images with pics of the graphs and overlay the text with the graph info, then when clicked on, it opens the graphs/data's dedicated page where it goes in depth of what it is/etc. Phantom demo:
https://pixelarity.com/items/demos/phantom/magenta/
