### ISSUE TITLE
Enlarge Twitter/GitHub links on mobile

### ISSUE THREAD

**Issue by curtisbarnard** [20jasper/100Devs-Statistics-Project#28]
They are currently pretty small and close together so it's a bit difficult to click them on a mobile screen. They should be maybe 50% or more larger and have some padding between them.

**Comment by bytesbybianca** [comment]
I want to grab this one once we've merged the latest contributor bio.

**Comment by 20jasper** [comment]
@bytesbybianca just merged it, you're good to go

**Comment by bytesbybianca** [comment]
#32
