### ISSUE TITLE
Refine the data scraper

### ISSUE THREAD

**Issue by 20jasper** [20jasper/100Devs-Statistics-Project#36]
Right now it only takes information from one page and returns the information in a data frame

Refine the scraper so that it
- [ ] scrapes every page of Leon's streams
- [ ] returns the data in an easy to work with format (I know how to parse data easily from a CSV, but other formats should work too if that's not easy)

**Comment by nfolkman** [comment]
Currently brainstorming the issue.
(See Discord - "data-scraping")
