### ISSUE TITLE
Move favicon images to the assets folder

### ISSUE THREAD

**Issue by 20jasper** [20jasper/100Devs-Statistics-Project#45]
Move favicon images to the assets folder (maybe make an icon folder within it) and change their links accordingly

**Comment by Lovegupta112** [comment]
Do you mean favicon images??

**Comment by 20jasper** [comment]
Yep, I think it's a little cluttered now, and we already made an image folder, so makes sense to organize it a little bit more

**Comment by Lovegupta112** [comment]
I think that you should read this , bcz this is very important for favicon 😊
![Screenshot_20220407-092721](https://user-images.githubusercontent.com/90507983/162117652-3187cbd9-82fd-48b0-aa2d-47d6238424eb.png)

**Comment by 20jasper** [comment]
Ok thank you, I guess I've just never had multiple versions of the favicon on a page before
