### ISSUE TITLE
Make a contributers page on the site

### ISSUE THREAD

**Issue by 20jasper** [20jasper/100Devs-Statistics-Project#6]
I'm not sure if this can be automated, but anyone who has pushed code or contributed ideas can be on the page
We should add everyone's names, githubs, and twitters

**Comment by curtisbarnard** [comment]
I could work on this this weekend. Could you assign the issue to me? It doesn't look like I have permissions to assign myself.

**Comment by curtisbarnard** [comment]
I have a contributors branch on my local machine that I'm working on this. It doesn't seem like I have permissions to push it up to this repo. @20jasper could you look into permissions and see if something is blocking me?

**Comment by DekotaNelson** [comment]
Fork repo to your repo -> make branch for your task -> perform task -> push to your forked repo's task branch -> pull request -> approved and merged. This is the way. It gives practice to the way it's done in big companies, open source projects, etc. It also makes the changes more streamlined and clean 👍

**Comment by curtisbarnard** [comment]
@DekotaNelson got it! I'm working on another project with people and they were doing branches on the main repo and I didn't have to fork so I assumed that's what we would do here. Thanks for the clarification

**Comment by curtisbarnard** [comment]
This can be marked complete once #13 PR goes thru.
