### ISSUE TITLE
Deploy the site

### ISSUE THREAD

**Issue by curtisbarnard** [20jasper/100Devs-Statistics-Project#7]
I think you could use Github pages to deploy the site it's pretty simple, let me know if you need to know how. Alternative could be netlify.

**Comment by DekotaNelson** [comment]
If we use netlify we can utilize their form service, so users could easily send issues or anything

**Comment by 20jasper** [comment]
I just deployed it on netlify a few minutes ago. If for whatever reason it doesn't work for us, we can always change the hosting service
