### ISSUE TITLE
update hamburger menu

### ISSUE THREAD

**Issue by curtisbarnard** [20jasper/100Devs-Statistics-Project#8]
Need to update menu sidebar to only include home and contributors.

**Comment by DekotaNelson** [comment]
Once we have the contributor page would be happy to perform this. Or, if there's anyone wanting a good first issue, this is a good one. Let me know if someone else wants to take a shot at it.

**Comment by Yuji-Itadorii** [comment]
@curtisbarnard, @20jasper   I would like to work on it, please assign this issue to me.

First of all, I want to confirm that the wanted hamburger menu should look just similar to the below image or something else?
<img width="946" alt="image" src="https://user-images.githubusercontent.com/93515450/161285900-c14b601f-562d-4b45-ba23-158ad110a311.png">

**Comment by curtisbarnard** [comment]
@Abhay2002r If we have only two pages it might be worth it to ditch the horizontal rule? Not sure if there are any other pages we need to add?

edit: the html file is contributors.html and will be in the root directory if you want to work on it right now. I'm going to probably get it finished and have a PR ready by EOD tomorrow I think.

**Comment by 20jasper** [comment]
@Abhay2002r Yep, that looks good. The contributors page is up now, so you can link it too

**Comment by Yuji-Itadorii** [comment]
Hey @20jasper, I have updated the hamburger menu in the index.html and contributor.html file and linked the contributors.html file. I have sent a pull request, please review it and merge it and let me know if there is any issue you found.

**Comment by 20jasper** [comment]
Looks good to me
